version: "3.8"

services:
  app:
    build: .
    ports:
      - "10000:10000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - SERVICE_TOKEN=${SERVICE_TOKEN}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
    volumes:
      - .:/app
      - /app/vendor
    command: php -S 0.0.0.0:10000 -t public
    # Optional for debugging (uncomment if needed)
    # environment:
    #   - XDEBUG_MODE=debug
    #   - XDEBUG_CONFIG=client_host=host.docker.internal
